# Dependencies
markdown:         redcarpet
highlighter:      pygments

# Permalinks
permalink:        pretty
#relative_permalinks: true

# Setup
title:            New York Area Exoplanets I
tagline:          ''
description:      ''
url:              /
baseurl:          /

author:
  name:           ''
  url:            /

gems:                [jekyll-paginate]
paginate:            5
paginate_path:       "page:num"

# Custom vars
version:          2.1.0

github:
  repo:           /
